name: "Daily Build"
on:
  workflow_dispatch:
jobs:
  windows-build-jvm-latest:
    name: Daily - Windows - JVM build - Latest Version
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Install Quarkus CLI
        shell: pwsh
        run: |
          $linesToWrite = @"
          @ECHO OFF
          CHCP 65001
          "@
          New-Item -Path "$env:USERPROFILE\quarkus-dev-cli.bat" -ItemType File
          Set-Content -Path "$env:USERPROFILE\quarkus-dev-cli.bat" -Value $linesToWrite
          get-content "$env:USERPROFILE\quarkus-dev-cli.bat"
      - name: Build in JVM mode
        shell: bash
        run: |
          cd C:\Users\runneradmin
          
          ./quarkus-dev-cli.bat
          mvn -v
