name: "Daily Build"
on:
  workflow_dispatch:
jobs:
  windows-build-jvm-latest:
    name: Daily - Windows - JVM build - Latest Version
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 21 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Set up Maven settings.xml
        run: |
          Copy-Item -Path ".github\quarkus-snapshots-mvn-settings.xml" -Destination "$env:USERPROFILE\.m2\settings.xml"
          dir "$env:USERPROFILE\.m2\"
      - name: Download Quarkus CLI
        shell: bash
        run: mvn -B --no-transfer-progress org.apache.maven.plugins:maven-dependency-plugin:get -Dartifact=io.quarkus:quarkus-cli:999-SNAPSHOT:jar:runner
      - name: Install Quarkus CLI
        run: |
          $quarkusCliFileContent = @"
          @ECHO OFF
          java -jar %HOMEDRIVE%%HOMEPATH%\.m2\repository\io\quarkus\quarkus-cli\999-SNAPSHOT\quarkus-cli-999-SNAPSHOT-runner.jar %*
          "@
          New-Item -Path "$(pwd)\quarkus-dev-cli.bat" -ItemType File
          Set-Content -Path "$(pwd)\quarkus-dev-cli.bat" -Value $quarkusCliFileContent
          ./quarkus-dev-cli.bat version
      - name: Build in JVM mode
        shell: bash
        run: |
          # Need to set UTF-8 as otherwise the cp1252 is used on GH windows runner
          # TODO revisit this with Windows 2025 when available or when we move testing to JDK 21+ only
          export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
          mvn help:effective-settings
