name: "Daily Build"
on:
  workflow_dispatch:
jobs:
  windows-build-jvm-latest:
    name: Daily - Windows - JVM build - Latest Version
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Install Quarkus CLI
        shell: pwsh
        run: |
          Invoke-WebRequest https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkus/quarkus-cli/999-SNAPSHOT/quarkus-cli-999-20241209.023002-1284-runner.jar -OutFile "$(pwd)\quarkus-cli-999-SNAPSHOT-runner.jar"
          New-Item -Path "$(pwd)\quarkus-dev-cli.bat" -ItemType File
          Set-Content -Path "%cd%\quarkus-dev-cli.bat" -Value 'java -jar "%cd%\quarkus-cli-999-SNAPSHOT-runner.jar" %*'
          get-content "$(pwd)\quarkus-dev-cli.bat"
          cd "$(pwd)"
          ./quarkus-dev-cli.bat version
      - name: Build in JVM mode
        shell: pwsh
        run: |
          mvn -v
