name: "Daily Build"
on:
  workflow_dispatch:
jobs:
  windows-build-jvm-latest:
    name: Daily - Windows - JVM build - Latest Version
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Set up Maven settings.xml # we need to do this because of CLI and external app tests does not propagate '-s' option
        shell: bash
        run: cp .github/quarkus-snapshots-mvn-settings.xml ~/.m2/settings.xml
      - name: Download Quarkus CLI
        shell: bash
        run: mvn -B --no-transfer-progress org.apache.maven.plugins:maven-dependency-plugin:get -Dartifact=io.quarkus:quarkus-cli:999-SNAPSHOT:jar:runner
      - name: Install Quarkus CLI
        shell: pwsh
        run: |
          New-Item -Path "$(pwd)\quarkus-dev-cli.bat" -ItemType File
          Set-Content -Path "$(pwd)\quarkus-dev-cli.bat" -Value 'java -jar "%HOMEDRIVE%%HOMEPATH%\.m2\repository\io\quarkus\quarkus-cli\999-SNAPSHOT\quarkus-cli-999-SNAPSHOT-runner.jar" %*'
          get-content "$(pwd)\quarkus-dev-cli.bat"
          ./quarkus-dev-cli.bat version
      - name: Build in JVM mode
        shell: pwsh
        run: |
          mvn -v
